ALTER TABLE public.tls_secrets
ADD COLUMN IF NOT EXISTS cert TEXT,
ADD COLUMN IF NOT EXISTS private_key TEXT,
ADD COLUMN IF NOT EXISTS not_before TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITH TIME ZONE;
